const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="bamigboyeraymond21@gmail.com"
global.location="ekiti, Nigeria."


global.mongodb= process.env.MONGODB_URI || "Mongodb+srv://DARKSHAN:3000@cluster0.t1wsjlv.mongodb.net/"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://chat.whatsapp.com/DrkuCkLXUs32wyBFmBnSUA";
global.website=process.env.GURL || "https://chat.whatsapp.com/DrkuCkLXUs32wyBFmBnSUA" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 



global.devs = "2349163103803”// Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349163103803";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "TRUE", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "2349163103803";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_18_23_05_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA0LFxuICAgICAgICAxNjIsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjQzLFxuICAgICAgICA2LFxuICAgICAgICA0MyxcbiAgICAgICAgMTY5LFxuICAgICAgICAxMDMsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTU5LFxuICAgICAgICA3MixcbiAgICAgICAgNjAsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTEzLFxuICAgICAgICAzMCxcbiAgICAgICAgMjE1LFxuICAgICAgICAyMDYsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjA5LFxuICAgICAgICAxNjgsXG4gICAgICAgIDg1LFxuICAgICAgICAxNTIsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTIxLFxuICAgICAgICAxNyxcbiAgICAgICAgMTkzLFxuICAgICAgICAyMzIsXG4gICAgICAgIDgyLFxuICAgICAgICAxOTAsXG4gICAgICAgIDEwNSxcbiAgICAgICAgNzEsXG4gICAgICAgIDkyXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjU0LFxuICAgICAgICA0MSxcbiAgICAgICAgOTMsXG4gICAgICAgIDE5NixcbiAgICAgICAgODAsXG4gICAgICAgIDY4LFxuICAgICAgICAxMDgsXG4gICAgICAgIDE5LFxuICAgICAgICAzNSxcbiAgICAgICAgMTgsXG4gICAgICAgIDk4LFxuICAgICAgICA1NyxcbiAgICAgICAgMjAxLFxuICAgICAgICA0MyxcbiAgICAgICAgMjMwLFxuICAgICAgICA2NixcbiAgICAgICAgNzUsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjgsXG4gICAgICAgIDIxMyxcbiAgICAgICAgNTQsXG4gICAgICAgIDE2LFxuICAgICAgICAxMzgsXG4gICAgICAgIDI1LFxuICAgICAgICA4NCxcbiAgICAgICAgNCxcbiAgICAgICAgNTIsXG4gICAgICAgIDg2LFxuICAgICAgICA5NyxcbiAgICAgICAgMjMyLFxuICAgICAgICAxMjNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2LFxuICAgICAgICAyNDAsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTA4LFxuICAgICAgICAzNyxcbiAgICAgICAgMTc5LFxuICAgICAgICAxOTYsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjAsXG4gICAgICAgIDQ2LFxuICAgICAgICAxNzcsXG4gICAgICAgIDc2LFxuICAgICAgICA0NCxcbiAgICAgICAgMTY1LFxuICAgICAgICA2MCxcbiAgICAgICAgMTE1LFxuICAgICAgICA5NCxcbiAgICAgICAgMjQ1LFxuICAgICAgICAyMDksXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTAzLFxuICAgICAgICAxMjEsXG4gICAgICAgIDk1LFxuICAgICAgICAyMjMsXG4gICAgICAgIDY4LFxuICAgICAgICAxMzksXG4gICAgICAgIDMxLFxuICAgICAgICA3NyxcbiAgICAgICAgMTUxLFxuICAgICAgICAxNjAsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTIwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQyLFxuICAgICAgICAyMjIsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTg1LFxuICAgICAgICA5OCxcbiAgICAgICAgMTcxLFxuICAgICAgICA0MSxcbiAgICAgICAgMjQ4LFxuICAgICAgICAyMyxcbiAgICAgICAgMjE2LFxuICAgICAgICA2MSxcbiAgICAgICAgMTcxLFxuICAgICAgICA2MSxcbiAgICAgICAgNDIsXG4gICAgICAgIDUxLFxuICAgICAgICAxMjUsXG4gICAgICAgIDE4MixcbiAgICAgICAgMjIsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTc0LFxuICAgICAgICAyMTEsXG4gICAgICAgIDYwLFxuICAgICAgICAxMDksXG4gICAgICAgIDEyNCxcbiAgICAgICAgNDEsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxNzgsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTc0LFxuICAgICAgICAxMixcbiAgICAgICAgODNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDgwLFxuICAgICAgICAxOTEsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTE0LFxuICAgICAgICAxMjAsXG4gICAgICAgIDQ4LFxuICAgICAgICAxOTQsXG4gICAgICAgIDU3LFxuICAgICAgICAxMzAsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTMyLFxuICAgICAgICAyMTcsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTgwLFxuICAgICAgICAxNjAsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMixcbiAgICAgICAgNCxcbiAgICAgICAgMTAzLFxuICAgICAgICAxNixcbiAgICAgICAgNjUsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjIsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTA5LFxuICAgICAgICAyMzEsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjA5LFxuICAgICAgICA3MyxcbiAgICAgICAgNTUsXG4gICAgICAgIDksXG4gICAgICAgIDY0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1OSxcbiAgICAgICAgOTAsXG4gICAgICAgIDExLFxuICAgICAgICAxNDcsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjExLFxuICAgICAgICA0NSxcbiAgICAgICAgMjA0LFxuICAgICAgICAyMjUsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNTIsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMjQxLFxuICAgICAgICAxNTEsXG4gICAgICAgIDksXG4gICAgICAgIDgxLFxuICAgICAgICAxNzUsXG4gICAgICAgIDIxMCxcbiAgICAgICAgNTIsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTcwLFxuICAgICAgICA1OSxcbiAgICAgICAgNjAsXG4gICAgICAgIDg5LFxuICAgICAgICAyNDYsXG4gICAgICAgIDEwLFxuICAgICAgICAxMjAsXG4gICAgICAgIDE3MCxcbiAgICAgICAgOTYsXG4gICAgICAgIDE1NSxcbiAgICAgICAgOTdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMyxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICAzNSxcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA1NixcbiAgICAgICAgICAxMTJcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDIsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICA0MixcbiAgICAgICAgICAzMixcbiAgICAgICAgICA0NCxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDExOFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDksXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTE4LFxuICAgICAgICA2NCxcbiAgICAgICAgMjE2LFxuICAgICAgICA3MixcbiAgICAgICAgOTYsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMjQxLFxuICAgICAgICAyMDcsXG4gICAgICAgIDUyLFxuICAgICAgICA0LFxuICAgICAgICAxMDUsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNzAsXG4gICAgICAgIDU0LFxuICAgICAgICAyNDgsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTk1LFxuICAgICAgICAxOTksXG4gICAgICAgIDMxLFxuICAgICAgICA1OSxcbiAgICAgICAgODYsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNTQsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjI1LFxuICAgICAgICAxNzEsXG4gICAgICAgIDU2LFxuICAgICAgICAyMixcbiAgICAgICAgMjAsXG4gICAgICAgIDE4OCxcbiAgICAgICAgODMsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTEzLFxuICAgICAgICAxNzMsXG4gICAgICAgIDMyLFxuICAgICAgICAyNTMsXG4gICAgICAgIDQxLFxuICAgICAgICAxOCxcbiAgICAgICAgODYsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjA4LFxuICAgICAgICAyMzUsXG4gICAgICAgIDEzLFxuICAgICAgICAyNTUsXG4gICAgICAgIDUsXG4gICAgICAgIDE4NixcbiAgICAgICAgNSxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMDksXG4gICAgICAgIDUzLFxuICAgICAgICAxMTEsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTgyLFxuICAgICAgICAxOCxcbiAgICAgICAgMTY0LFxuICAgICAgICAzMyxcbiAgICAgICAgMTk1LFxuICAgICAgICAxNjgsXG4gICAgICAgIDU5LFxuICAgICAgICAzNyxcbiAgICAgICAgMTM5XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxOCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJMMndqSEI1dmYxNGIzY1pNaE8xK2c0YW1WOVRNTURpZk1mbEZoYzhYRlFrPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDgxNDM3Mjg2OTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjBERTBFRjA2MjNDNkFDN0VBQTcyQzJFQjRDQjA4QjBCXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDkzMzQzMVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDgxNDM3Mjg2OTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjdBMTZBNEM3MDQ4RDg3MzIzOEFFQURDNDg2RDY4ODg1XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDkzMzQzMlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDgxNDM3Mjg2OTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkZCRkEwNjAxMjQ1MTY2OUFCNUFEQjZBQTVEMTYyNDY2XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDkzMzQzNFxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDgxNDM3Mjg2OTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjM3Mzc1NzkxQUNENzc3NDdGMkM4OUVEMzdCRTE3MTg0XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDkzMzQzNVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJaU0lJQ2pGYVFUQ1IyQ0NwTDBRa3l3XCIsXG4gIFwicGhvbmVJZFwiOiBcIjE4NTkzNDYwLTMyNmEtNDc2OC1iNTg2LWEyMzVhM2Y4ODBiMVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA1MyxcbiAgICAgIDIzOCxcbiAgICAgIDI1MixcbiAgICAgIDE0NCxcbiAgICAgIDM3LFxuICAgICAgMTgsXG4gICAgICA5LFxuICAgICAgMTE3LFxuICAgICAgMjA5LFxuICAgICAgMTM2LFxuICAgICAgMTMwLFxuICAgICAgMTk3LFxuICAgICAgMyxcbiAgICAgIDIxNCxcbiAgICAgIDEyOCxcbiAgICAgIDk2LFxuICAgICAgNjYsXG4gICAgICAxNzAsXG4gICAgICA2NSxcbiAgICAgIDI0NVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyNDksXG4gICAgICA1MCxcbiAgICAgIDE4LFxuICAgICAgMTQzLFxuICAgICAgMTY1LFxuICAgICAgMTYwLFxuICAgICAgMTk4LFxuICAgICAgMTQ0LFxuICAgICAgMjE0LFxuICAgICAgMTcyLFxuICAgICAgODksXG4gICAgICA2LFxuICAgICAgMTM5LFxuICAgICAgMTgzLFxuICAgICAgMTA1LFxuICAgICAgMjMsXG4gICAgICAyNTQsXG4gICAgICAxMzIsXG4gICAgICAxOSxcbiAgICAgIDk4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIkdDWkRKN1hZXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ4MTQzNzI4NjkwOjEyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxMjM0MDc3ODE4NzU3OTc6MTJAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiUmF5bW9uZCBCYWNrdXBcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNQM0ppY29GRUxHZDM3RUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIkFNYVVVU0s3bUEzckxxZnVremd5aGppa2lqMHpNVzlrSG5aenZEQUwrUlE9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiREYyKzJubWFUTDZieDlGNXhFMFh4UFRacEMyei9yNGRXdDhiNEZBQnF4c082VEJ2Znd2cldublBjeDQxcHlHeUZwUStZRHdNOEtYcmNWbjFiLzYvRFE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiWFpWK0hVZEs2V1R3WmdsK2NkL09FSkxpMEk4VXZ3aHk0czFwRUQ5RzZPc0F1NHllaFZhMnF1YVVBV01ObEd4UWRvZkt2dHVhYzlLVE81b29ma0d4Z3c9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0ODE0MzcyODY5MDoxMkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDIzNSxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICA1NixcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTY0LFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAyMFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzE0OTMzNDI4LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRGRJXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFEZEkuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJIMGFuRUxKdjV0MC9mNFNwVi9idDgyTzd2bU9qeTVEZ1RqN1E0V3hwRERjPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE0OTc1MjM0NTMsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcxNDkzMzQzMjE4MlwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.4",
  caption : process.env.CAPTION || "©RAY" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "RAY MD",
  ownername:process.env.OWNER_NAME||"RAYMOND",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
